import { test } from "node:test";
import assert from "node:assert/strict";
import { parseEnv } from "../src/env-parser.js";
import { buildExampleContent } from "../src/generator.js";

test("parseEnv handles basic key=value", () => {
  const env = parseEnv("FOO=bar\nBAZ=qux");
  assert.equal(env.get("FOO"), "bar");
  assert.equal(env.get("BAZ"), "qux");
});

test("parseEnv strips matching quotes", () => {
  const env = parseEnv(`A="hello world"\nB='single'`);
  assert.equal(env.get("A"), "hello world");
  assert.equal(env.get("B"), "single");
});

test("parseEnv ignores comments and blank lines", () => {
  const env = parseEnv("# comment\n\nFOO=bar\n  # indented comment\n");
  assert.equal(env.size, 1);
  assert.equal(env.get("FOO"), "bar");
});

test("parseEnv keeps empty values", () => {
  const env = parseEnv("EMPTY=");
  assert.equal(env.get("EMPTY"), "");
});

test("buildExampleContent appends new vars to existing content", () => {
  const scan = new Map([
    ["EXISTING", [{ file: "a.js", line: 1 }]],
    ["NEW_VAR", [{ file: "b.js", line: 5 }]],
  ]);
  const existing = "# my notes\nEXISTING=value123\n";
  const { content, added, existing: kept } = buildExampleContent(scan, existing);

  assert.deepEqual(added, ["NEW_VAR"]);
  assert.deepEqual(kept, ["EXISTING"]);
  // Hand-written value and comment preserved.
  assert.match(content, /# my notes/);
  assert.match(content, /EXISTING=value123/);
  // New var appended with location comment.
  assert.match(content, /# used in b\.js:5/);
  assert.match(content, /NEW_VAR=/);
});

test("buildExampleContent generates fresh file when none exists", () => {
  const scan = new Map([["ONLY", [{ file: "x.js", line: 2 }]]]);
  const { content, added } = buildExampleContent(scan, null);
  assert.deepEqual(added, ["ONLY"]);
  assert.match(content, /Generated by envscan/);
  assert.match(content, /ONLY=/);
});

test("buildExampleContent sorts variables alphabetically", () => {
  const scan = new Map([
    ["ZEBRA", [{ file: "a.js", line: 1 }]],
    ["ALPHA", [{ file: "a.js", line: 2 }]],
  ]);
  const { added } = buildExampleContent(scan, null);
  assert.deepEqual(added, ["ALPHA", "ZEBRA"]);
});
