import { readFile, writeFile } from "node:fs/promises";

/**
 * Build the text content for a .env.example file from scan results.
 *
 * If an existing .env.example is provided, variables already present in it
 * keep their existing line (value + any inline comment) so hand-written
 * descriptions and example values are preserved. Newly discovered variables
 * are appended with a comment showing where they're first referenced.
 *
 * @param {Map<string, Array<{file: string, line: number}>>} scanResults
 * @param {string|null} existingContent - current .env.example text, or null
 * @returns {{ content: string, added: string[], existing: string[] }}
 */
export function buildExampleContent(scanResults, existingContent) {
  const names = [...scanResults.keys()].sort();

  // Figure out which names already exist in the current file.
  const existingKeys = new Set();
  if (existingContent) {
    for (const raw of existingContent.split("\n")) {
      const line = raw.trim();
      if (!line || line.startsWith("#")) continue;
      const eq = line.indexOf("=");
      if (eq > 0) existingKeys.add(line.slice(0, eq).trim());
    }
  }

  const added = names.filter((n) => !existingKeys.has(n));
  const existing = names.filter((n) => existingKeys.has(n));

  // Preserve the existing file verbatim, then append a block for new vars.
  const parts = [];

  if (existingContent && existingContent.trim()) {
    parts.push(existingContent.replace(/\n+$/, ""));
  } else {
    parts.push("# Generated by envscan — fill in the values below.");
  }

  if (added.length > 0) {
    if (existingContent && existingContent.trim()) {
      parts.push(""); // blank separator
      parts.push("# --- Added by envscan ---");
    }
    for (const name of added) {
      const refs = scanResults.get(name);
      const first = refs[0];
      parts.push(`# used in ${first.file}:${first.line}`);
      parts.push(`${name}=`);
    }
  }

  return {
    content: parts.join("\n") + "\n",
    added,
    existing,
  };
}

/**
 * Generate or update a .env.example file on disk.
 *
 * @param {Map} scanResults
 * @param {string} outputPath - path to .env.example
 * @returns {Promise<{ added: string[], existing: string[] }>}
 */
export async function generate(scanResults, outputPath) {
  let existingContent = null;
  try {
    existingContent = await readFile(outputPath, "utf8");
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }

  const { content, added, existing } = buildExampleContent(
    scanResults,
    existingContent
  );

  await writeFile(outputPath, content, "utf8");
  return { added, existing };
}
